services:
  postgres:
    image: postgres:16
    container_name: vendly_postgres
    restart: always
    environment:
      POSTGRES_USER: vendly_user
      POSTGRES_PASSWORD: vendly_pass
      POSTGRES_DB: vendly
    ports:
      - "55433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: vendly_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: